# Название нашего workflow
name: Run tests and deploy "bot-generate"

# Условия запуска workflow - в нашем случае при каждом пуше в репозиторий
on:
  push:
    paths:
      - 'generate/bot-generate.py'

# Определяем задачи (jobs), которые будут выполняться в рамках workflow
jobs:
  # Задача с именем "test"
  test:
    # Запускаем задачу на виртуальной машине с Ubuntu
    runs-on: ubuntu-latest

    # Определяем шаги (steps) для выполнения задачи
    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Check out repository
        uses: actions/checkout@v2

      # Шаг 2: Устанавливаем нужную версию Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Шаг 3: Устанавливаем зависимости (в нашем случае фреймворк для тестирования pytest и telebot)
      - name: Install dependencies
        run: pip install pytest telebot

      # Шаг 4: Запускаем юнит-тесты с помощью pytest
      - name: Run tests
        run: python generate/bot-generate.py
        env:
          generate_bot: ${{ secrets.generate_bot }}

# Задача с именем "deploy"
  deploy:
    # Запускаем задачу на виртуальной машине с Ubuntu
    runs-on: ubuntu-latest

    # Задаем зависимость от задачи "test"
    needs: test

    # Определяем шаги (steps) для выполнения задачи
    steps:
      # Шаг 1: Копируем файл на удаленный сервер с помощью scp
      - name: Copy file to remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.generate_ssh_known_hosts }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.generate_ssh_private_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp generate/bot-generate.py ${{ secrets.username }}@${{ secrets.remote_host }}:${{ secrets.generate_path_to_destination }}