# Название нашего workflow
name: Run unit tests

# Условия запуска workflow - в нашем случае при каждом пуше в репозиторий
on: push

# Определяем задачи (jobs), которые будут выполняться в рамках workflow
jobs:
  # Задача с именем "test"
  test:
    # Запускаем задачу на виртуальной машине с Ubuntu
    runs-on: ubuntu-latest

    # Определяем шаги (steps) для выполнения задачи
    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Check out repository
        uses: actions/checkout@v2

      # Шаг 2: Устанавливаем нужную версию Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Шаг 3: Устанавливаем зависимости (в нашем случае фреймворк для тестирования pytest)
      - name: Install dependencies
        run: pip install pytest

      # Шаг 4: Запускаем юнит-тесты с помощью pytest
      - name: Run tests
        run: pytest
